### PR TITLE
Escaping prisoners has been caught.

### PR DESCRIPTION
**Pull request by regener**
Minor lang update

### CODE REVIEW

**Comment by evandrocoan** [comment]
Thanks. I recently added this:
```
GAL_VOTE_GO_TO_PAGE = Go to a menu's page
```
How would be its translation?

image

**Comment by regener** [comment]
Oh sorry, I have just remembered that from dev version before the release.

That would translate to:

`GAL_VOTE_GO_TO_PAGE = Menü oldalra ugrás`

**Comment by evandrocoan** [comment]
No problems.

**Comment by evandrocoan** [comment]
Why you requested this on the master branch?
It should be on the develop branch as your other pull requests.

**Comment by regener** [comment]
That is a good question. Sorry for that too.

**Comment by evandrocoan** [comment]
No problem, is pretty easy to mistake something.

**Pull request merged**
